### ISSUE TITLE
Do not use mailchimp API listing all members to count subscriptions

### ISSUE THREAD

**Issue by sergray** [OpenbookOrg/openbook-org-api#31]
[openbook_org_contact.views.WaitlistSubscribeView.post#L95](https://github.com/OpenbookOrg/openbook-org-api/blob/master/openbook_org_contact/views.py#L95) retrieves the list with all the members and uses it to count subscriptions.

This is a problematic call, since resource usage (memory, CPU) is proportional to amount of the members.

Subscriptions should be counted locally to the Org API.

**Comment by sergray** [comment]
It is actually possible to retrieve the total count of subscribers without fetching all members.
Mailchimp [GET /lists/{list_id}/members](
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#read-get_lists_list_id_members) API 3.0 accepts optional parameter `count`, specifying how many records to retrieve and returns `total_items`. So the fix would be to set `count=0` and use `total_items` value.

**Comment by uiboy** [comment]
@sergray we were already using that API, changed it to `count=0` and using the total items now 🙏  Thank you for your suggestion 👍

**Comment by lifenautjoe** [comment]
Thanks @sergray !

**Comment by sergray** [comment]
No problem. Glad to help.
